import renderStatistics from './renderStatistics.js';
import game from './game.js';
import backend from './backend.js';
import setup from './setup.js';
import dialog from './dialog.js';
dialog();
import form from './form.js';
import render from './render.js';
import debounce from './debounce.js';
import update from './update.js';
import wizard from './wizard.js';
import avatar from './avatar.js';
avatar();
import style from '../scss/style.scss';
